{"name": "test_sign_in_invalid_number2", "status": "passed", "description": "the test is verify, that user can't sign in with invalid number", "start": 1680536480960, "stop": 1680536481469, "uuid": "9143af5c-4f26-459f-a87a-3706c6ed0112", "historyId": "695a0dfd0628b584141d81304ab2e006", "testCaseId": "a0fc73048fc817bf816b80e6772439dc", "fullName": "tests.edgeTests.testSignInModal.TestSignInModal#test_sign_in_invalid_number2", "labels": [{"name": "parentSuite", "value": "tests.edgeTests"}, {"name": "suite", "value": "testSignInModal"}, {"name": "subSuite", "value": "TestSignInModal"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "19772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.edgeTests.testSignInModal"}]}