{"name": "test_sign_in_invalid_number1", "status": "passed", "description": "the test is verify, that user can't sign in with invalid number", "start": 1680536473969, "stop": 1680536474682, "uuid": "32d381bc-39c8-4b90-b0d3-3ca78ca29261", "historyId": "ddc25602f009f2be16dbe6ee67a5e267", "testCaseId": "0713592a78e5333e0f4bbe741105041c", "fullName": "tests.edgeTests.testSignInModal.TestSignInModal#test_sign_in_invalid_number1", "labels": [{"name": "parentSuite", "value": "tests.edgeTests"}, {"name": "suite", "value": "testSignInModal"}, {"name": "subSuite", "value": "TestSignInModal"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "19772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.edgeTests.testSignInModal"}]}