{"name": "test_sign_in_invalid_number3", "status": "passed", "description": "the test is verify, that user can't sign in with invalid number", "start": 1680536486351, "stop": 1680536486960, "uuid": "c50bee73-985f-487a-a64d-4bffa07c1f09", "historyId": "ffdfcd30f95939b2884959076ba1b86c", "testCaseId": "b167780cb4f57dd587aab38d74693a63", "fullName": "tests.edgeTests.testSignInModal.TestSignInModal#test_sign_in_invalid_number3", "labels": [{"name": "parentSuite", "value": "tests.edgeTests"}, {"name": "suite", "value": "testSignInModal"}, {"name": "subSuite", "value": "TestSignInModal"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "19772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.edgeTests.testSignInModal"}]}