{"name": "test_invalid_bn_number_saved_in_db", "status": "failed", "statusDetails": {"message": "AssertionError: assert '3333333333' != ('3' * 10)\n +  where '3333333333' = <function get_user_id at 0x000001EE6AAF0940>()\n +    where <function get_user_id at 0x000001EE6AAF0940> = db.get_user_id", "trace": "self = <tests.dbTests.test_DB.TestDB object at 0x000001EE6AC8B370>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"57107c06f1c13fe4ffa31c5b6ec656c4\")>\n\n    @allure.description(\"the test is verify, if the data hasn't been saved to the database\"\n                        \" after the user has edited the business number\")\n    def test_invalid_bn_number_saved_in_db(self, driver):\n        self.sign_in_modal.sign_in()\n        self.home_page.personal_area_hdr_click()\n        self.personal_area_page.edit_btn_click()\n        self.personal_area_page.set_bn_id_num(\"3\" * 10)\n        self.personal_area_page.save_btn_click()\n>       assert db.get_user_id() != '3' * 10\nE       AssertionError: assert '3333333333' != ('3' * 10)\nE        +  where '3333333333' = <function get_user_id at 0x000001EE6AAF0940>()\nE        +    where <function get_user_id at 0x000001EE6AAF0940> = db.get_user_id\n\ntests\\dbTests\\test_DB.py:19: AssertionError"}, "description": "the test is verify, if the data hasn't been saved to the database after the user has edited the business number", "start": 1680536614803, "stop": 1680536619187, "uuid": "266eb7e1-d1a6-41ef-a5b4-8a8937d36051", "historyId": "198256b06522eec93a4b2cd7fa2236ce", "testCaseId": "4575182622cf988a5e704cf638010a1f", "fullName": "tests.dbTests.test_DB.TestDB#test_invalid_bn_number_saved_in_db", "labels": [{"name": "parentSuite", "value": "tests.dbTests"}, {"name": "suite", "value": "test_DB"}, {"name": "subSuite", "value": "TestDB"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "19772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.dbTests.test_DB"}]}